### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by zachovo** [Li-Kunyi/dns-slam#1]
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    slam = DNS_SLAM(cfg, device)
  File "/data2/xnf/dns-slam-main/slams/dns_slam.py", line 77, in __init__
    workbook = openpyxl.load_workbook(xlsx_file_path)
  File "/home/xnf/miniconda3/envs/dns-slam/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 347, in load_workbook
    data_only, keep_links, rich_text)
  File "/home/xnf/miniconda3/envs/dns-slam/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/home/xnf/miniconda3/envs/dns-slam/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "/home/xnf/miniconda3/envs/dns-slam/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/xnf/demo_replica_room_0/room_0/imap/00/semantic2color.xlsx'

I'm having this issue when running the code. Although there may be a problem with the path in the warning, I really didn't look for this file, why is that?

**Comment by zachovo** [comment]
I didn't look for "semantic2color.xlsx"

**Comment by AAAAAurora** [comment]
I had the same problem as you, did you find a solution？

**Comment by li-kunyi** [comment]
> I had the same problem as you, did you find a solution？

hi, we updated dns_slam.py and removed the requirement of semantic2color.xlsx.

**Comment by AAAAAurora** [comment]
> dns_slam

Okay, thank you！
